#
# RTEMS Tools Project (http://www.rtems.org/)
# Copyright (C) 2024 Phytium Technology Co., Ltd.
# All rights reserved.
#
# This file is part of the RTEMS Tools package in 'rtems-tools'.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

#
# The AArch64 Phytium PI BSP.
#
[phytium_pi]
bsp                = phytium_pi
arch               = aarch64
tester             = %{_rtscripts}/tftp.cfg
jobs               = 1
bsp_tty_dev        = 127.0.0.1:2000
test_restarts      = 3
target_power_ctrl_tool  = /home/gitlab-runner/test_tool/phytium-test-tools/test_tool
target_pretest_command = cd %{target_power_ctrl_tool} && python3 ./board_power_ctrl.py reset
target_posttest_command = #post test
target_on_command  = 
target_off_command = 
# reset target board if target_reset_regex matched
target_reset_command = cd %{target_power_ctrl_tool} && python3 ./board_power_ctrl.py reset
target_reset_regex = ^Autonegotiation timed out*|^.*: link down*|^ARP Retry count exceeded*|^No elf image at address*
target_start_regex = Phytium-Pi*|phytium-pi*
requires           = target_on_command, target_off_command, target_reset_command, bsp_tty_dev

# enable ser2net service in host and we access serial through telnent 127.0.0.1 2000
#   sudo apt-get install ser2net
#   sudo nano /etc/ser2net.yaml # add below code to mapping /dev/ttyAMA2 to port 2000
#   connection: &con0096
#        accepter: tcp,2000
#        enable: on
#        options:
#        banner: ""
#        kickolduser: true
#        telnet-brk-on-sync: true
#        connector: serialdev,
#                /dev/ttyAMA2,
#                115200n81,local
#   sudo systemctl restart ser2net
#   sudo service tftpd-hpa stop

# define below command in u-boot to autoloading rtems image after reset
#   setenv ipaddr 192.168.4.20
#   setenv serverip 192.168.4.50
#   setenv gatewayip 192.168.4.1
#   setenv bootcmd "tftpboot 0xd0100000 rtems.exe; bootelf -s 0xd0100000;"
#   saveenv